<?php

namespace AppBundle\Repository;

/**
 * Place_to_eatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Place_to_eatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAddedPlacesToEat () {
        $q = $this->getEntityManager()->createQuery('
        SELECT p.name, p.coordsLongitude, p.coordsLatitude, p.adress, p.town, p.id FROM AppBundle:Place_to_eat p
        ');
        return $q->getResult();
    }
}
