<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlaces () {
        $q = $this->getEntityManager()->createQuery('
        SELECT p.name, p.coordsLongitude, p.coordsLatitude, p.adress, p.city, p.id FROM AppBundle:Place p
        ');
        return $q->getResult();
    }
}
