<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlaces() {
        $q = $this->getEntityManager()->createQuery('
        SELECT p.name, p.coordsLongitude, p.coordsLatitude, p.adress, p.id, p.likeSpot FROM AppBundle:Place p
        ');
        return $q->getResult();
    }

    public function findPlace($param) {
        $q = $this->getEntityManager()->createQuery('
        SELECT p.name, p.coordsLongitude, p.coordsLatitude, p.adress, p.id, p.likeSpot FROM AppBundle:Place p WHERE p.name = :name
        ');
        $q->setParameters([
            'name' => $param
        ]);
        return $q->getResult();
    }

    public function findAllByChars($param) {
        $q = $this->getEntityManager()->createQuery('
            SELECT p.name FROM AppBundle:Place p WHERE p.name LIKE :param
        ');
        $q->setParameters([
            'param' => "%".$param."%"
        ]);
        return $q->getResult();
    }

    public function incrementCounter($param) {
        return $this->createQueryBuilder('p')
            ->update('AppBundle:Place', 'p')
            ->set('p.likeSpot', 'p.likeSpot + 1')
            ->where('p.name = :param')
            ->setParameter('param', $param)
            ->getQuery()
            ->execute();
    }

    public function retrieveLike($param) {
        $q = $this->getEntityManager()->createQuery('
        SELECT p.likeSpot FROM AppBundle:Place p WHERE p.name = :name
        ');
        $q->setParameters([
            'name' => $param
        ]);
        return $q->getResult();
    }
}
